### ISSUE TITLE
ページ全体の設定を追加

### ISSUE THREAD

**Issue by KoyoIshikawa** [yanbaru-expert/team_project_38#3]
## 実装内容

ページ全体に共通する内容が書かれているファイル `app/views/layouts/application.html.erb` にスマホ用のビューポートを設定しておきましょう。

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

【参考】https://developers.google.com/web/fundamentals/design-and-ux/responsive?hl=ja#set-the-viewport

さらに，

```erb
    <%= yield %>
```

を

```erb
    <header>
    </header>
    <main>
      <#% max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
```

としておき，全ページに共通して必要なCSSを `app/assets/stylesheets/application.css` に設定して下さい。

```css
/* 全体 */ 

.base-container {
  margin: 0 auto;
  padding: 1rem;
}

/* max-width */ 

.mw-md {
  max-width: 720px;
}

.mw-lg {
  max-width: 960px;
}

.mw-xl {
  max-width: 1200px;
}
```

さらに，`max_width` メソッドを `app/helpers/application_helper.rb` に定義しましょう。後に条件分岐が必要ですが，現時点では `mw-xl` 固定としておきましょう。

```rb
module ApplicationHelper
  def max_width
    "mw-xl"
  end
end
```
